### ISSUE TITLE
Unable to install and/or build (Android)

### ISSUE THREAD

**Issue by 45kb** [donaldp24/CanvasCameraPlugin#15]
Hello, sorry for the issue, i get problems i just tried installing plugin:

cordova plugin add com.keith.cordova.plugin.canvascamera

i get this error:

Error: 404 Not Found: com.keith.cordova.plugin.canvascamera
    at RegClient.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:268:14)
    at Request.self.callback (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:148:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:876:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:827:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)

So i used this:

cordova plugin add https://github.com/donaldp24/CanvasCameraPlugin.git && cordova prepare

But when i launch:

cordova build android && cordova run android

i get error:

BUILD FAILED
/usr/local/opt/android-sdk/tools/ant/build.xml:720: The following error occurred while executing this line:
/usr/local/opt/android-sdk/tools/ant/build.xml:734: Compile failed; see the compiler error output for details.

Total time: 3 seconds

Any clue?

**Comment by gmccrackin** [comment]
Have you checked if its #7.

**Comment by 45kb** [comment]
@gmccrackin  Thank you but i don't get it, is that fixed somewhere?  Should i try something?

**Comment by stephan-nordnes-eriksen** [comment]
+1 The specific error:

```
[javac] /path/to/my/project/platforms/android/src/com/keith/canvascameraplugin/CanvasCameraView.java:87: error: package R does not exist
....
```

There are many of these "package R does not exist". From the file mentioned above, i see `setContentView(R.layout.canvascamera);`. This `R` is not there. Digging a bit around I suspect this is the issue: http://stackoverflow.com/questions/12986301/package-r-does-not-exist. However, when I try to add `import android.R;` I get new errors. Is it possibly not android.R that is being used?

**Comment by JakeRuth** [comment]
+1 
I am somewhat new to phonegap.  However, linking to your plugin in my config.xml file leaves phonegap build tool in an error state for Android with no meaningful error message.  

I am sure of this because I built my project before putting in the line in the config.xml and everything build fine, however changing just one line and adding the plugin link in my config.xml breaks the build.  That one line for sure, that was the only change I made.

If this could be fixed that would be great, I am really in need of an in app camera for my app.

**Comment by stephan-nordnes-eriksen** [comment]
I have made a branch which solves this on ios. You might want to check it out. I did not make a PR since it changes the behaviour, and only on iOS for now. 

https://github.com/stephan-nordnes-eriksen/CordovaCameraPreview

**Comment by JakeRuth** [comment]
Thanks for the reply @stephan-nordnes-eriksen , however I believe that this problem resides in adroid only.  There appears to be a PR for it already that has been outstanding for a while https://github.com/donaldp24/CanvasCameraPlugin/pull/7/files 

Unfortunately it appears that the owner of this repo hasn't logged in for a while.  I am debating on releasing another version of the plugin but it would be better if it got re-released by someone who would be able to handle issues and keep it in working order.

**Comment by gmccrackin** [comment]
I think this is a great idea. I would like to do it but I don't think I have the time. If someone does it thought I would try and help contribute as much as possible.

**Comment by stephan-nordnes-eriksen** [comment]
@JakeRuth Woops! I posted that in the wrong comment field! Sorry. It is totally for another plugin. Sorry

**Comment by JakeRuth** [comment]
Its totally fine @stephan-nordnes-eriksen :)
So sometime this week I will (hopefully) look into re launching this plugin with the merge request [#7](https://github.com/donaldp24/CanvasCameraPlugin/pull/7) incorporated in master.  However in the long run I am probably going to switch my app code over to React Native, which is coming out soon.  React Native should be fixing many of the problems phonegap presents so hopefully these headaches will go away.

**Comment by gmccrackin** [comment]
I am also excited to see React Native released! I think it will solve many of the problems I have with cordova also!
