### ISSUE TITLE
Android Compile Failed.

### ISSUE THREAD

**Issue by crapthings** [donaldp24/CanvasCameraPlugin#6]
monsterstep:canvascamera zhanghong$ meteor run android-platform
Error while running for mobile platforms: Error running /Users/zhanghong/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh

BUILD FAILED
/Users/zhanghong/.meteor/android_bundle/android-sdk/tools/ant/build.xml:720: The following error occurred while executing this line:
/Users/zhanghong/.meteor/android_bundle/android-sdk/tools/ant/build.xml:734: Compile failed; see the compiler error output for details.

Total time: 6 seconds
Error code 1 for command: ant with args: debug,-f,/Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/build.xml,-Dout.dir=ant-build,-Dgen.absolute.dir=ant-gen
Error: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/Users/zhanghong/.meteor/packages/meteor-tool/.1.0.35.wql4jh++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/dev_bundle/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Process.ChildProcess._handle.onexit (child_process.js:822:5)

Running command: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/cordova/build
Buildfile: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/build.xml

-set-mode-check:

-set-debug-files:

-check-env:
 [checkenv] Android SDK Tools Revision 23.0.2
 [checkenv] Installed at /Users/zhanghong/.meteor/android_bundle/android-sdk

-setup:
     [echo] Project Name: canvascamera
  [gettype] Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
[getbuildtools] Using latest Build Tools: 21.0.0
     [echo] Resolving Build Target for canvascamera...
[gettarget] Project Target:   Android 4.4.2
[gettarget] API level:        19
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/ant-build
    [mkdir] Created dir: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/ant-build/res
    [mkdir] Created dir: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/ant-build/rsObj
    [mkdir] Created dir: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/ant-build/rsLibs
    [mkdir] Created dir: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/ant-gen
    [mkdir] Created dir: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/ant-build/classes
    [mkdir] Created dir: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/ant-build/dexedLibs
     [echo] ----------
     [echo] Resolving Dependencies for canvascamera...
[dependency] Library dependencies:
[dependency]
[dependency] ------------------
[dependency] Ordered libraries:
[dependency]
[dependency] ------------------
     [echo] ----------
     [echo] Building Libraries with 'debug'...

nodeps:

-set-mode-check:

-set-debug-files:

-check-env:
 [checkenv] Android SDK Tools Revision 23.0.2
 [checkenv] Installed at /Users/zhanghong/.meteor/android_bundle/android-sdk

-setup:
     [echo] Project Name: CordovaLib
  [gettype] Project Type: Android Library

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
[getbuildtools] Using latest Build Tools: 21.0.0
     [echo] Resolving Build Target for CordovaLib...
[gettarget] Project Target:   Android 4.4.2
[gettarget] API level:        19
     [echo] ----------
     [echo] Creating output directories if needed...
    [mkdir] Created dir: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/CordovaLib/res
    [mkdir] Created dir: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/CordovaLib/libs
    [mkdir] Created dir: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build
    [mkdir] Created dir: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/res
    [mkdir] Created dir: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/rsObj
    [mkdir] Created dir: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/rsLibs
    [mkdir] Created dir: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-gen
    [mkdir] Created dir: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/classes
    [mkdir] Created dir: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/dexedLibs
     [echo] ----------
     [echo] Resolving Dependencies for CordovaLib...
[dependency] Library dependencies:
[dependency] No Libraries
[dependency]
[dependency] ------------------

-code-gen:
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Generating resource IDs...
     [echo] ----------
     [echo] Handling BuildConfig class...
[buildconfig] Generating BuildConfig class.

-pre-compile:

-compile:
    [javac] Compiling 90 source files to /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/classes
    [javac] warning: [options] source value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 3 warnings
     [echo] Creating library output jar file...
      [jar] Building jar: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/classes.jar

-post-compile:

-obfuscate:

-dex:
     [echo] Library project: do not convert bytecode...

-crunch:
   [crunch] Crunching PNG Files in source dir: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/CordovaLib/res
   [crunch] To destination dir: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/res
   [crunch] Crunched 0 PNG files to update cache

-package-resources:
     [echo] Library project: do not package resources...

-package:
     [echo] Library project: do not package apk...

-post-package:

-do-debug:
     [echo] Library project: do not create apk...
[propertyfile] Creating new property file: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/build.prop
[propertyfile] Updating property file: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/build.prop
[propertyfile] Updating property file: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/build.prop
[propertyfile] Updating property file: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/build.prop

-post-build:

debug:

-code-gen:
[mergemanifest] Merging AndroidManifest files into one.
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Generating resource IDs...
     [echo] ----------
     [echo] Handling BuildConfig class...
[buildconfig] Generating BuildConfig class.

-pre-compile:
     [echo] Set jars path to: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/CordovaLib/ant-build/classes.jar

-compile:
    [javac] Compiling 29 source files to /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/ant-build/classes
    [javac] warning: [options] source value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/src/com/keith/canvascameraplugin/CanvasCameraView.java:87: error: package R does not exist
    [javac]         setContentView(R.layout.canvascamera);
    [javac]                         ^
    [javac] /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/src/com/keith/canvascameraplugin/CanvasCameraView.java:134: error: package R does not exist
    [javac]         m_imgFlash = (ImageView) findViewById(R.id.imgFlash);
    [javac]                                                ^
    [javac] /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/src/com/keith/canvascameraplugin/CanvasCameraView.java:136: error: package R does not exist
    [javac]         m_imgRevert = (ImageView) findViewById(R.id.imgRevert);
    [javac]                                                 ^
    [javac] /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/src/com/keith/canvascameraplugin/CanvasCameraView.java:137: error: package R does not exist
    [javac]         m_imgCapture = (ImageView) findViewById(R.id.imgCapture);
    [javac]                                                  ^
    [javac] /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/src/com/keith/canvascameraplugin/CanvasCameraView.java:138: error: package R does not exist
    [javac]         m_imgClose = (ImageView) findViewById(R.id.imgClose);
    [javac]                                                ^
    [javac] /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/src/com/keith/canvascameraplugin/CanvasCameraView.java:140: error: package R does not exist
    [javac]         m_surfaceview = (SurfaceView) findViewById(R.id.surfaceView);
    [javac]                                                     ^
    [javac] /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/src/com/keith/canvascameraplugin/CanvasCameraView.java:151: error: package R does not exist
    [javac]             m_imgFlash.setImageResource(R.drawable.video_sprites_focus_inactive);
    [javac]                                          ^
    [javac] /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/src/com/keith/canvascameraplugin/CanvasCameraView.java:153: error: package R does not exist
    [javac]             m_imgFlash.setImageResource(R.drawable.video_sprites_focus);
    [javac]                                          ^
    [javac] /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/src/com/keith/canvascameraplugin/CanvasCameraView.java:156: error: package R does not exist
    [javac]             m_imgRevert.setImageResource(R.drawable.video_sprites_revert);
    [javac]                                           ^
    [javac] /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/src/com/keith/canvascameraplugin/CanvasCameraView.java:158: error: package R does not exist
    [javac]             m_imgRevert.setImageResource(R.drawable.video_sprites_revert_inactive);
    [javac]                                           ^
    [javac] /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/src/com/keith/canvascameraplugin/CanvasCameraView.java:181: error: package R does not exist
    [javac]                 m_imgFlash.setImageResource(R.drawable.video_sprites_focus);
    [javac]                                              ^
    [javac] /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/src/com/keith/canvascameraplugin/CanvasCameraView.java:188: error: package R does not exist
    [javac]                 m_imgFlash.setImageResource(R.drawable.video_sprites_focus_inactive);
    [javac]                                              ^
    [javac] /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/src/com/keith/canvascameraplugin/CanvasCameraView.java:218: error: package R does not exist
    [javac]                 m_imgRevert.setImageResource(R.drawable.video_sprites_revert_inactive);
    [javac]                                               ^
    [javac] /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/src/com/keith/canvascameraplugin/CanvasCameraView.java:221: error: package R does not exist
    [javac]                 m_imgFlash.setImageResource(R.drawable.video_sprites_focus);
    [javac]                                              ^
    [javac] /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/src/com/keith/canvascameraplugin/CanvasCameraView.java:229: error: package R does not exist
    [javac]                 m_imgRevert.setImageResource(R.drawable.video_sprites_revert);
    [javac]                                               ^
    [javac] /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/src/com/keith/canvascameraplugin/CanvasCameraView.java:429: error: package R does not exist
    [javac]                 m_imgRevert.setImageResource(R.drawable.video_sprites_revert);
    [javac]                                               ^
    [javac] /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/src/com/keith/canvascameraplugin/CanvasCameraView.java:434: error: package R does not exist
    [javac]                 m_imgRevert.setImageResource(R.drawable.video_sprites_revert_inactive);
    [javac]                                               ^
    [javac] Note: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/file/DirectoryManager.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: /Users/zhanghong/dev/canvascamera/.meteor/local/cordova-build/platforms/android/src/org/apache/cordova/file/ContentFilesystem.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 17 errors
    [javac] 3 warnings

monsterstep:canvascamera zhanghong$

**Comment by gmccrackin** [comment]
I believe this might fix your problem e9f0b1959bacd8b0370d2593e7967bbb6efaf6a3.
